# Generated by Django 3.1.3 on 2021-01-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServed',
            fields=[
                ('name', models.CharField(help_text='Is it World wide service website or for specific area', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a website industry (e.g. e-commerce)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('user_picture', models.ImageField(blank=True, help_text='Upload the picture of user.', null=True, upload_to='')),
                ('bio', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_domain_name', models.CharField(help_text='Website hostname without sub-domain and top-level-domain', max_length=71, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Enter a brief description of the website', max_length=1000)),
                ('founded', models.DateField(blank=True, help_text='When was this website created?', null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='When was this page created?')),
                ('brand_picture', models.ImageField(blank=True, help_text="Upload the picture of website's brand.", null=True, upload_to='')),
                ('headquarters', models.CharField(blank=True, help_text='The location where most of the important functions of an organization are coordinated.', max_length=200)),
                ('numberOfEmployees', models.CharField(blank=True, max_length=200, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('areaServed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.areaserved')),
                ('founders', models.ManyToManyField(blank=True, help_text='Who made this website?', to='website.Founder')),
                ('industry', models.ManyToManyField(blank=True, help_text='Select a type for this website', to='website.Industry')),
                ('subsidiaries', models.ManyToManyField(blank=True, help_text='the companies that is owned or controlled by this company', max_length=200, related_name='_website_subsidiaries_+', to='website.Website')),
                ('writen_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
            options={
                'ordering': ['-likes', 'dislikes', 'name'],
            },
        ),
        migrations.AddField(
            model_name='founder',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='When was this page created?')),
                ('comment', models.CharField(max_length=600)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('rate_to_web', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
                ('website_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
        ),
    ]
