# Generated by Django 3.1.3 on 2021-01-14 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0002_auto_20201225_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('user_picture', models.ImageField(blank=True, help_text='Upload the picture of user.', null=True, upload_to='')),
                ('bio', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profile'),
        ),
        migrations.AlterField(
            model_name='website',
            name='writen_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
