# Generated by Django 3.1.3 on 2021-01-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210115_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
            options={
                'unique_together': {('website', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteDislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.website')),
            ],
            options={
                'unique_together': {('website', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile')),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.profile')),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
