# Generated by Django 3.1 on 2021-02-04 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_commentdislike_commentlikes_websitedislikes_websitelikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_table',
            field=models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_table',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(blank=True, help_text='Upload the picture of user.', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='website',
            name='brand_picture',
            field=models.ImageField(blank=True, help_text="Upload the picture of website's brand.", null=True, upload_to='img'),
        ),
    ]
